string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef run_id)
set(output "${WORK}/${run_id}")
execute_process(COMMAND "${BUILDER}" frequency --source "${SOURCE}" --output "${output}"
    RESULT_VARIABLE result ERROR_VARIABLE error)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Frequency conversion failed: ${error}")
endif()
execute_process(COMMAND "${TESTER}" "${output}/character-score.tsv" RESULT_VARIABLE result)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Frequency tests failed")
endif()
execute_process(COMMAND "${BUILDER}" frequency --source "${SOURCE}" --output "${output}-second"
    RESULT_VARIABLE result)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Second conversion failed")
endif()
file(SHA256 "${output}/character-score.tsv" first)
file(SHA256 "${output}-second/character-score.tsv" second)
if(NOT first STREQUAL second)
    message(FATAL_ERROR "Frequency conversion not deterministic")
endif()
foreach(name tsi.csv word.csv README.upstream.md COPYING.LGPL-2.1.txt provenance.json source.zip)
    file(SHA256 "${SOURCE}/${name}" original)
    file(SHA256 "${output}/sources/${name}" copied)
    if(NOT original STREQUAL copied)
        message(FATAL_ERROR "Source preservation failed: ${name}")
    endif()
endforeach()
