string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef run_id)
set(output "${WORK}/${run_id}")
execute_process(COMMAND "${BUILDER}" build --source "${STROKE_SOURCE}" --output "${output}/stroke" --scope traditional RESULT_VARIABLE result ERROR_VARIABLE error)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Stroke fixture conversion failed: ${error}")
endif()
foreach(name first second)
    execute_process(COMMAND "${BUILDER}" phrases --source "${SOURCE}" --index "${output}/stroke/dictionary.sidx" --output "${output}/${name}" RESULT_VARIABLE result ERROR_VARIABLE error)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Phrase conversion failed: ${error}")
    endif()
endforeach()
file(SHA256 "${output}/first/phrases.pidx" first)
file(SHA256 "${output}/second/phrases.pidx" second)
if(NOT first STREQUAL second)
    message(FATAL_ERROR "Phrase conversion is not deterministic")
endif()
execute_process(COMMAND "${TESTER}" "${output}/first/phrases.pidx" RESULT_VARIABLE result)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Real phrase tests failed")
endif()
execute_process(COMMAND "${BUILDER}" phrases --source "${SOURCE}" --index "${output}/stroke/dictionary.sidx" --output "${output}/first" RESULT_VARIABLE result)
if(result EQUAL 0)
    message(FATAL_ERROR "Builder overwrote existing phrase output")
endif()
foreach(name tsi.csv provenance.json COPYING.LGPL-2.1.txt source.zip)
    file(SHA256 "${SOURCE}/${name}" original)
    file(SHA256 "${output}/first/sources/${name}" copied)
    if(NOT original STREQUAL copied)
        message(FATAL_ERROR "Phrase source preservation failed: ${name}")
    endif()
endforeach()

# A controlled CSV exercises max-score merging and the filters independently of upstream size.
file(MAKE_DIRECTORY "${output}/fixture")
foreach(name provenance.json COPYING.LGPL-2.1.txt source.zip)
    file(COPY "${SOURCE}/${name}" DESTINATION "${output}/fixture")
endforeach()
file(WRITE "${output}/fixture/tsi.csv" "# dc:license,LGPL-2.1-or-later,\n你好,2,ㄋㄧˇ ㄏㄠˇ\n你好,8,ㄋㄧˊ ㄏㄠˇ\n一,4,ㄧ\n你好世界你好世界你,5,fixture\n你好😀,3,fixture\n")
execute_process(COMMAND "${BUILDER}" phrases --source "${output}/fixture" --index "${output}/stroke/dictionary.sidx" --output "${output}/fixture-result" RESULT_VARIABLE result)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Controlled phrase conversion failed")
endif()
file(READ "${output}/fixture-result/phrases.pidx" index)
if(NOT index MATCHES "你好\t8\n$")
    message(FATAL_ERROR "Repeated pronunciations did not merge by maximum priority")
endif()
file(READ "${output}/fixture-result/report.tsv" report)
foreach(expected "single_rows\t1\n" "length_filtered\t1\n" "unsupported_rows\t1\n" "merged_readings\t1\n" "phrases\t1\n")
    string(FIND "${report}" "${expected}" position)
    if(position EQUAL -1)
        message(FATAL_ERROR "Controlled filter count mismatch: ${expected}")
    endif()
endforeach()
file(WRITE "${output}/fixture/tsi.csv" "# dc:license,LGPL-2.1-or-later,\n你好,-1,fixture\n")
execute_process(COMMAND "${BUILDER}" phrases --source "${output}/fixture" --index "${output}/stroke/dictionary.sidx" --output "${output}/bad-score" RESULT_VARIABLE result)
if(result EQUAL 0 OR EXISTS "${output}/bad-score")
    message(FATAL_ERROR "Invalid score was accepted or produced output")
endif()
